---
- name: Enable main Gluster 3 repo with GA packages
  command: "subscription-manager repos --enable=rh-gluster-3-for-rhel-7-server-rpms"
#  when: gluster_puddle_repo == ''

- name: Create additional repo with downstream packages for Gluster 3
  yum_repository:
    name: "downstream-rh-gluster-3-for-rhel-7-server-rpms"
    baseurl: "{{ gluster_puddle_repo }}"
    description: "Downstream repo with development versions of packages for Gluster 3"
    enabled: "yes"
    gpgcheck: "no"
    sslverify: "no"
    cost: 990
  when: gluster_puddle_repo != ''
