---
# OpenShift variables
openshift_master_cluster_hostname: "{{ lb_host }}"
openshift_master_cluster_public_hostname: "{{ lb_host }}"
console_port: 8443
openshift_vers: "{{ openshift_vers | default('v3_6')}}"
openshift_major_version: "{{ openshift_vers.split('_')[-1] }}"
openshift_ansible_branch: release-3.{{ openshift_major_version }}
openshift_required_repos:
- rhel-7-server-rpms
- rhel-7-server-extras-rpms
- rhel-7-server-ose-3.{{ openshift_major_version }}-rpms
- rhel-7-fast-datapath-rpms
# 'openshift_node_groups' is required for OCP3.10
openshift_node_groups:
- name: node-config-master
  labels:
  - 'node-role.kubernetes.io/master=true'
  - 'role=master'
  edits: []
- name: node-config-compute
  labels:
    - 'node-role.kubernetes.io/compute=true'
    - 'node-role.kubernetes.io/infra=true'
    - 'role=compute'
  edits: []
- name: node-config-storage
  labels:
    - 'node-role.kubernetes.io/storage=true'
    - 'role=storage'
  edits: []
