---
- hosts: new_nodes
  gather_facts: yes
  become: yes
  vars_files:
  - vars/main.yaml
  roles:
  - package-repos

- hosts: new_nodes
  gather_facts: no
  become: yes
  vars_files:
  - vars/main.yaml
  roles:
  - prerequisites
