---
- include: prod-ose-crs.yaml
  tags: ['vms']

- include: crs-node-setup.yaml
  tags: [ 'node-setup' ]

- include: crs-setup.yaml
  tags: [ 'node-setup']

- include: cleanup-crs.yaml
  tags: ['clean']
