---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  # Group systems
  - create-vm-cns-prod-ose
  - setup-custom-domain-names-for-ansible-runner
