---
- hosts: localhost
  vars_files:
    - vars/main.yaml
  roles:
    - create-vm-prod-ose
    - setup-custom-domain-names-for-ansible-runner

- name: fulfill OSE3 prerequisites on production hosts roles
  hosts: production_group
  vars_files:
    - vars/main.yaml
  roles:
    - setup-custom-domain-names
    - package-repos
    - vmware-guest-setup
    - cloud-provider-setup
    - docker-storage-setup
    - openshift-volume-quota
  ignore_errors: yes
