---
- include: "{{ (openshift_vers in ['v3_6', 'v3_7']) |
               ternary(
                   lookup('env', 'VIRTUAL_ENV') +
                       '/usr/share/ansible/openshift-ansible/playbooks/' +
                       'byo/openshift-node/scaleup.yml',
                   'noop.yaml')
           }}"

- include: "{{ (openshift_vers in ['v3_9']) |
               ternary(
                   lookup('env', 'VIRTUAL_ENV') +
                       '/usr/share/ansible/openshift-ansible/playbooks/' +
                       'openshift-node/scaleup.yml',
                   'noop.yaml')
           }}"

# NOTE(vponomar): following playbooks are what we need from
# 'playbooks/openshift-node/scaleup.yml' playbook in OCP3.10 and OCP3.11
# It may be changed for OCP3.11+ versions.
- include: "{{ (openshift_vers not in ['v3_6', 'v3_7', 'v3_9']) | 
               ternary(
                   lookup('env', 'VIRTUAL_ENV') +
                       '/usr/share/ansible/openshift-ansible/playbooks/' +
                       'openshift-node/private/bootstrap.yml',
                   'noop.yaml')
           }}"

- include: "{{ (openshift_vers not in ['v3_6', 'v3_7', 'v3_9']) | 
               ternary(
                   lookup('env', 'VIRTUAL_ENV') +
                       '/usr/share/ansible/openshift-ansible/playbooks/' +
                       'openshift-node/private/join.yml',
                   'noop.yaml')
           }}"
